---
- name: Rollback ExpenseHub Deployment
  hosts: production
  become: yes
  vars_files:
    - vars/production.yml

  tasks:
    - name: Get previous git commit
      shell: cd {{ app_directory }} && git log --oneline -2 | tail -1 | awk '{print $1}'
      register: previous_commit
      become_user: "{{ ansible_user }}"

    - name: Display rollback target
      debug:
        msg: "Rolling back to commit: {{ previous_commit.stdout }}"

    - name: Confirm rollback
      pause:
        prompt: "Press Enter to continue with rollback or Ctrl+C to cancel"

    - name: Stop containers
      command: docker compose down
      args:
        chdir: "{{ app_directory }}"
      become_user: "{{ ansible_user }}"

    - name: Checkout previous commit
      git:
        repo: "{{ git_repo }}"
        dest: "{{ app_directory }}"
        version: "{{ previous_commit.stdout }}"
        force: yes
      become_user: "{{ ansible_user }}"

    - name: Rebuild and start containers
      command: docker compose up -d --build
      args:
        chdir: "{{ app_directory }}"
      become_user: "{{ ansible_user }}"

    - name: Wait for application
      wait_for:
        port: 80
        delay: 10
        timeout: 60

    - name: Verify rollback
      uri:
        url: "http://localhost/api/health"
        status_code: 200
      register: health_check
      retries: 3
      delay: 5
      until: health_check.status == 200

    - name: Display success message
      debug:
        msg: "Rollback completed successfully to commit {{ previous_commit.stdout }}"

